### ISSUE TITLE
"Status not determined" message 

### ISSUE THREAD

**Issue by nidalios** [Vuframe/PanicAR#29]
I have used your framework and it was working perfect on iOS7 so I purchased the license , on iOS8 I updated the framework but keep getting me "Status not determined" error message. why is that happening? Please I need urgent help to fix my app

**Comment by kevincador** [comment]
I'm getting a message PSK_STATUS_DENIED with the version v2.2.3025. The .plist doesn't have that key anymore. I'm testing with both camera and location disabled. Could you please check? Thanks.

**Comment by rudyjahchan** [comment]
I am also having this issue. When I try to use the v2.2.305 `.podspec` file, `pod install` outputs the following:

```
Installing PanicAR 2.2.3017 (was 2.1.2672)

[!] Error installing PanicAR
[!] /usr/local/bin/git clone https://github.com/doPanic/PanicAR.git /var/folders/zq/6p9tk2093_lbn8ybbffr8tk00000gn/T/d20150818-18088-10d1ygf --single-branch --depth 1 --branch 2.2.3017

Cloning into '/var/folders/zq/6p9tk2093_lbn8ybbffr8tk00000gn/T/d20150818-18088-10d1ygf'...
warning: Could not find remote branch 2.2.3017 to clone.
fatal: Remote branch 2.2.3017 not found in upstream origin
```

Will try `beta` using the `git` properties in the `Podfile` next.
