### ISSUE TITLE
Newer SDK with warning

### ISSUE THREAD

**Issue by leearmstrong** [Vuframe/PanicAR#32]
I believe you still support back to iOS7 but you now get warnings in Xcode that the SDK was compiled with iOS8.

I believe it still works but would be nice for a clean compilation
![2015-08-21_14-37-58](https://cloud.githubusercontent.com/assets/82891/9409408/39490816-4812-11e5-8610-3e169bff7e2e.jpeg)

**Comment by leearmstrong** [comment]
No comments?

**Comment by azeitler** [comment]
thanks, lee. we're gonna consider it for the next release.

**Comment by azeitler** [comment]
ios 8 is now the default compile target.
