### ISSUE TITLE
BitCode Support

### ISSUE THREAD

**Issue by leearmstrong** [Vuframe/PanicAR#33]
Hi guys,

Do you plan on releasing an SDK shortly after iOS9 release with BitCode support enabled at all?

**Comment by leearmstrong** [comment]
?

**Comment by leearmstrong** [comment]
Is PanicAR even supported any more?

**Comment by johndpope** [comment]
??? bump

**Comment by johndpope** [comment]
<img width="727" alt="screen shot 2016-03-15 at 6 23 24 pm" src="https://cloud.githubusercontent.com/assets/289994/13799301/3ab1190c-eadb-11e5-9207-3306ec7a0dab.png">

**Comment by johndpope** [comment]
Days are numbered with Apple acquiring metaio. This will be out of the box in ios 10. http://techcrunch.com/2015/05/28/apple-metaio/

**Comment by leearmstrong** [comment]
But this isn't metaio, this is PanicAR?

**Comment by leearmstrong** [comment]
@azeitler If this has been abandoned can we at least have the source so we can recompile with BitCode support and the community pick it up some how?

**Comment by azeitler** [comment]
included in v3.0 beta – just released!
